# Generated by Django 3.2.8 on 2021-10-11 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20211009_2320'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeployTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=64, verbose_name='标识')),
                ('tag', models.CharField(max_length=32, verbose_name='版本')),
                ('status', models.IntegerField(choices=[(1, '待发布'), (2, '发布中'), (3, '成功'), (4, '失败')], default=1, verbose_name='状态')),
                ('before_download_script', models.TextField(blank=True, null=True, verbose_name='下载前脚本')),
                ('after_download_script', models.TextField(blank=True, null=True, verbose_name='下载后脚本')),
                ('before_deploy_script', models.TextField(blank=True, null=True, verbose_name='发布前脚本')),
                ('after_deploy_script', models.TextField(blank=True, null=True, verbose_name='发布后脚本')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.project', verbose_name='项目环境')),
            ],
        ),
    ]
