# Generated by Django 3.2.8 on 2021-10-12 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_node'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.server', verbose_name='服务器'),
        ),
    ]
